//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutTest) DeepCopyInto(out *RolloutTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutTest.
func (in *RolloutTest) DeepCopy() *RolloutTest {
	if in == nil {
		return nil
	}
	out := new(RolloutTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RolloutTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutTestList) DeepCopyInto(out *RolloutTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RolloutTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutTestList.
func (in *RolloutTestList) DeepCopy() *RolloutTestList {
	if in == nil {
		return nil
	}
	out := new(RolloutTestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RolloutTestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutTestSpec) DeepCopyInto(out *RolloutTestSpec) {
	*out = *in
	in.JobTemplate.DeepCopyInto(&out.JobTemplate)
	if in.UpstreamGate != nil {
		in, out := &in.UpstreamGate, &out.UpstreamGate
		*out = new(RolloutTestUpstreamGate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutTestSpec.
func (in *RolloutTestSpec) DeepCopy() *RolloutTestSpec {
	if in == nil {
		return nil
	}
	out := new(RolloutTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutTestStatus) DeepCopyInto(out *RolloutTestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpstreamGate != nil {
		in, out := &in.UpstreamGate, &out.UpstreamGate
		*out = new(RolloutTestUpstreamGateStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutTestStatus.
func (in *RolloutTestStatus) DeepCopy() *RolloutTestStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutTestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutTestUpstreamGate) DeepCopyInto(out *RolloutTestUpstreamGate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutTestUpstreamGate.
func (in *RolloutTestUpstreamGate) DeepCopy() *RolloutTestUpstreamGate {
	if in == nil {
		return nil
	}
	out := new(RolloutTestUpstreamGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutTestUpstreamGateStatus) DeepCopyInto(out *RolloutTestUpstreamGateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutTestUpstreamGateStatus.
func (in *RolloutTestUpstreamGateStatus) DeepCopy() *RolloutTestUpstreamGateStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutTestUpstreamGateStatus)
	in.DeepCopyInto(out)
	return out
}
