---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imagepolicies
  - imagerepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberik.com
  resources:
  - clusterrolloutschedules
  - healthchecks
  - kustomizationhealths
  - rolloutgates
  - rollouts
  - rolloutschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberik.com
  resources:
  - clusterrolloutschedules/finalizers
  - healthchecks/finalizers
  - kustomizationhealths/finalizers
  - rollouts/finalizers
  - rolloutschedules/finalizers
  verbs:
  - update
- apiGroups:
  - kuberik.com
  resources:
  - clusterrolloutschedules/status
  - healthchecks/status
  - kustomizationhealths/status
  - rollouts/status
  - rolloutschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.kuberik.com
  resources:
  - rollouttests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rollout.kuberik.com
  resources:
  - rollouttests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - ocirepositories
  verbs:
  - get
  - list
  - patch
  - update
  - watch
