---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imagepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberik.com
  resources:
  - healthchecks
  - kubestatuses
  - rolloutgates
  - rollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberik.com
  resources:
  - healthchecks/finalizers
  - kubestatuses/finalizers
  - rolloutgates/finalizers
  - rollouts/finalizers
  verbs:
  - update
- apiGroups:
  - kuberik.com
  resources:
  - healthchecks/status
  - kubestatuses/status
  - rolloutgates/status
  - rollouts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - ocirepositories
  verbs:
  - get
  - list
  - patch
  - update
  - watch
