apiVersion: kuberik.com/v1alpha1
kind: HealthCheck
metadata:
  labels:
    app.kubernetes.io/name: rollout-controller
    app.kubernetes.io/managed-by: kustomize
  name: healthcheck-sample
spec:
  # Class specifies the type of health check (e.g., 'kustomization')
  # +optional
  class: "kustomization"
