apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-app-kustomization
  namespace: default
  annotations:
    rollout.kuberik.com/frontend-rollout.substitute: "frontend_version"
    rollout.kuberik.com/backend-rollout.substitute: "backend_version"
    rollout.kuberik.com/api-rollout.substitute: "api_version"
spec:
  interval: 1m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-app-repo
  postBuild:
    substitute:
      frontend_version: "1.0.0" # Managed by frontend-rollout
      backend_version: "2.0.0" # Managed by backend-rollout
      api_version: "3.0.0" # Managed by api-rollout
