name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Generate Changelog
        run: make changelog-current

      - name: Build Kustomize Manifests
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          # Build installer with version tag
          make build-installer IMG=ghcr.io/${{ github.repository }}:${VERSION}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG-current.md
          files: |
            dist/install.yaml
